/* EBPF runtime library for programs generated by the P4 compiler */

#ifndef _EBPF_RUNTIME_H_
#define _EBPF_RUNTIME_H_

#include <stdint.h>
#include <stdlib.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef struct {
   u64 first;
   u64 second;
} u128;

#ifdef __cplusplus
extern "C" {
#endif

u8  unpack8 (const char* data, size_t offsetInBits, size_t bits);
u16 unpack16(const char* data, size_t offsetInBits, size_t bits);
u32 unpack32(const char* data, size_t offsetInBits, size_t bits);
u64 unpack64(const char* data, size_t offsetInBits, size_t bits);
u128 unpack128(const char* data, size_t offsetInBits, size_t bits);

#ifdef __cplusplus
}
#endif

#endif /* _EBPF_RUNTIME_H_ */
