/* EBPF runtime library for programs generated by the P4 compiler */

#include "ebpf_runtime.h"
#include <assert.h>

/* Unpack data from network-ordered data buffers.
   The output is always in host order */

u8 unpack8(const char* data, size_t offsetInBits, size_t bits) {
    assert(bits < 8);
    size_t firstByte = offsetInBits / 8;
    size_t lastByte = (offsetInBits + bits) / 8;
    size_t firstBit = offsetInBits % 8;
    size_t lastBit = firstBit + bits;
    u8 fb = data[firstByte];
    if (firstByte != lastByte) {
        u8 sb = data[lastByte];
        u16 two = ((u16)fb << 8) | (u16)sb;
        assert(lastBit <= 16);
        two >>= (16 - lastBit);
        return (u8)(two & 0xFF);
    }
    assert(lastBit <= 8);
    fb >>= (8 - lastBit);
    return fb;
}

u16 unpack16(const char* data, size_t offsetInBits, size_t bits) {
    return (u16)0;
}

u32 unpack32(const char* data, size_t offsetInBits, size_t bits) {
    return (u32)0;
}

u64 unpack64(const char* data, size_t offsetInBits, size_t bits) {
    return (u64)0;
}

u128 unpack128(const char* data, size_t offsetInBits, size_t bits) {
    u128 x = { 0, 0 };
    return x;
}
